version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ms_products